NumPy is an open source Python Library
NumPy Library = N-Dimensional Array + Package of functions

Key Features of NumPy:
1. Vectorized Operatiions
2. Linear Algebra Functions 
3. Integratiion with other Libraries
4. Fast Computation 

In [ ]:
# INSTALLING NUMPY

#pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [6]:
#importing numpy with alias np

import numpy  as np

Numpy Arrays

In [7]:
# CREATING NUMPY ARRAY
A1 = np.array([1,2,3,4,5])                       # 1D ARRAY
A2 = np.array([(1,2,3,4) , (5,6,7,8)])           # 2D ARRAY
A3 = np.array([[[1,2],[3,4]] , [[5,6],[7,8]]])   # 3D ARRAY
print(A1) 
print(A2)   
print(A3)   

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


INITIAL PLACEHOLDERS IN NUMPY ARRAYS

In [8]:
#create a numpy array of zeros
x  = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#creates a numpy array of oness
y = np.ones((4,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#create a identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
#create a  numpy array  with ramdom values

b = np.random.random((3,3))
print(b)

[[0.77213074 0.72045289 0.61310799]
 [0.02627209 0.18062528 0.46081023]
 [0.79228642 0.60097499 0.48650061]]


In [12]:
#random integer values array  with apecific range
c = np.random.randint(10,100, (3,3))
print(c)

[[31 30 24]
 [93 12 80]
 [38 42 86]]


In [13]:
#array of evenly spaced values -> specifying the number of values reuired
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [14]:
#array of evenly spaced values -> specifyiing the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [15]:
# convert a list to numpy array
list_2 = [10, 20 ,30, 40, 50]
np_array = np.asarray(list_2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

ANALYSING NUMPY ARRAY 

In [16]:
c = np.random.randint(10,90, (5,5))
print(c)

[[67 39 61 66 51]
 [67 11 47 71 32]
 [60 53 44 54 53]
 [19 47 57 22 23]
 [65 22 33 30 37]]


In [17]:
#array dimension
print(c.shape)

(5, 5)


In [18]:
# number of dimension
print(c.ndim)

2


In [19]:
#number  of element in an array
print(c.size)

25


In [20]:
#checking the datatye of the values in the array
print(c.dtype)

int32


MATHEMATICAL OPERATIOMNS ON NUMPY ARRAY

In [21]:
a = np.random.randint(10, 100, (3,3))
b = np.random.randint(10, 100, (3,3))

print(a)
print(b)

[[28 76 95]
 [17 66 86]
 [85 78 73]]
[[29 28 63]
 [54 22 43]
 [86 16 89]]


In [22]:
# ARITHMETIC OPERATIONS ON NUMPY ARRAYS
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 57 104 158]
 [ 71  88 129]
 [171  94 162]]
[[ -1  48  32]
 [-37  44  43]
 [ -1  62 -16]]
[[ 812 2128 5985]
 [ 918 1452 3698]
 [7310 1248 6497]]
[[0.96551724 2.71428571 1.50793651]
 [0.31481481 3.         2.        ]
 [0.98837209 4.875      0.82022472]]


In [23]:
# BINARY OPERATIONS ON NUMPY ARRAYS
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[ 57 104 158]
 [ 71  88 129]
 [171  94 162]]
[[ -1  48  32]
 [-37  44  43]
 [ -1  62 -16]]
[[ 812 2128 5985]
 [ 918 1452 3698]
 [7310 1248 6497]]
[[0.96551724 2.71428571 1.50793651]
 [0.31481481 3.         2.        ]
 [0.98837209 4.875      0.82022472]]


ARRAY MANIPULATION

In [24]:
array =np.random.randint(20,200, (4,5))
print(array)
print(array.shape)

[[170  79 132  21 191]
 [130  92 140 136 154]
 [ 91 174 132 150  53]
 [102 198  40 108 147]]
(4, 5)


In [25]:
#tranpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[170 130  91 102]
 [ 79  92 174 198]
 [132 140 132  40]
 [ 21 136 150 108]
 [191 154  53 147]]
(5, 4)


OR

In [26]:
#reshaping a array
a =np.random.randint(0,100, (3,4))
print(a)
print(a.shape)

[[ 6 56 23 85]
 [37 43 30 92]
 [27 42 14 13]]
(3, 4)


In [27]:
b =a.reshape(4,3)
print(b)
print(b.shape)

[[ 6 56 23]
 [85 37 43]
 [30 92 27]
 [42 14 13]]
(4, 3)
